server:
  port: 9002
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    exchangeName: bucketexchange
    queueName: bucketqueue
    routingKey: bucketelogs


minio:
  endpoint: http://localhost:9001
  accessKey: minioadmin
  secretKey: minioadmin
#  endpoint: http://192.168.15.234:32421
#  accessKey: wxfcAYflKOZofVva
#  secretKey: IlS8buLdLJR4RlHZzm5Y3lHDyy2qBSqn