server:
  port: 9002
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  endpoint: http://localhost:9001
#  endpoint: http://192.168.15.234:31657
  accessKey: minioadmin
  secretKey: minioadmin